# Generated by Django 5.2.8 on 2025-12-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("ADMIN", "Admin"), ("USER", "User")], default="USER", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="user_tag",
            field=models.CharField(default="@NewUser", max_length=30, unique=True),
        ),
    ]
