# Generated by Django 5.2.8 on 2025-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role_user_user_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_bg",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_tag",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
